name: Generate URL

on:
  workflow_dispatch:
  # schedule:
  # - cron: "0 2 * * 1-5"
jobs:
  generate-url:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: recursive  # サブモジュールを含めてリポジトリをチェックアウトする
 
    - name: Generate URL and save as artifact
      run: |
        # URL を生成する処理を実行するスクリプトを呼び出す
        generated_url=$(python find_and_generate_url.py)
        # 生成された URL をファイルに書き込む
        echo "$generated_url" > generated_url.txt
        echo "title=$(echo $generated_url | jq -r '.title')" >> $GITHUB_OUTPUT
        echo "title=$(echo $generated_url | jq -r '.url')" >> $GITHUB_OUTPUT
      # 生成された URL をアーティファクトとして保存する
      working-directory: .
    - name: Upload URL artifact
      uses: actions/upload-artifact@v4
      with:
        name: generated-url
        path: generated_url.txt
# nostrに投稿する
    - uses: snow-actions/nostr@v1.7.0
      with:
        relays: ${{ vars.NOSTR_RELAYS }}
        private-key: ${{ secrets.NOSTR_PRIVATE_KEY }}
        content: |
          ${{ steps.generate-url.outputs.title }}
          ${{ steps.generate-url.outputs.url }}
      id: publish
    - run: echo "${event}"
      env:
        event: ${{ steps.publish.outputs.event }}

